# Generated by Django 6.0.6 on 2026-06-13 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('level', models.IntegerField(default=0, verbose_name='級別')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='顏色')),
            ],
            options={
                'verbose_name': '優先級',
                'verbose_name_plural': '優先級',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設狀態')),
                ('is_closed', models.BooleanField(default=False, verbose_name='已關閉')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='顏色')),
            ],
            options={
                'verbose_name': '狀態',
                'verbose_name_plural': '狀態',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('icon', models.CharField(default='bi-bug', max_length=20, verbose_name='圖標')),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='顏色')),
            ],
            options={
                'verbose_name': '議題類型',
                'verbose_name_plural': '議題類型',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=500, verbose_name='摘要')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('labels', models.CharField(blank=True, help_text='逗號分隔', max_length=500, verbose_name='標籤')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project', verbose_name='專案')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='報告人')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issues.issuepriority', verbose_name='優先級')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issues.issuestatus', verbose_name='狀態')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issues.issuetype', verbose_name='類型')),
            ],
            options={
                'verbose_name': '議題',
                'verbose_name_plural': '議題',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue', verbose_name='議題')),
            ],
            options={
                'verbose_name': '評論',
                'verbose_name_plural': '評論',
                'ordering': ['created_at'],
            },
        ),
    ]
