# Generated by Django 6.0.6 on 2026-06-13 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='專案名稱')),
                ('key', models.CharField(help_text='簡短代號，例如 PROJ', max_length=10, unique=True, verbose_name='專案代號')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('project_type', models.CharField(choices=[('software', '軟體開發'), ('business', '商業專案'), ('personal', '個人專案'), ('other', '其他')], default='software', max_length=20, verbose_name='專案類型')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
            ],
            options={
                'verbose_name': '專案',
                'verbose_name_plural': '專案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理員'), ('member', '成員'), ('viewer', '檢視者')], default='member', max_length=10, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '專案成員',
                'verbose_name_plural': '專案成員',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
